export default {
  ADD_ITEM: 'ADD_ITEM', 
  EDIT_ITEM: 'EDIT_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  SELECT_ITEM: 'SELECT_ITEM',
  UNSELECT_ITEM: 'UNSELECT_ITEM',
  SHOW_FORM: 'SHOW_FORM',
  HIDE_FORM: 'HIDE_FORM',
  SELECT_ITEM_TO_EDIT: 'SELECT_ITEM_TO_EDIT'
}